text = "Neo-Nazism consists of post-World War II militant social or political movements seeking to revive and implement the ideology of Nazism. Neo-Nazis seek toemploy their ideology to promote hatred and attack minorities, or in some cases to create a fascist political state. It is a global phenomenon, with organized representation in many countries and international networks. It borrows elements from Nazi doctrine, including ultranationalism, racism, xenophobia, ableism, homophobia, anti-Romanyism, antisemitism, anti-communism and initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration of Adolf Hitler. In some European and Latin American countries, laws prohibit the expression of pro-Nazi, racist, anti-Semitic, or homophobic views. Many Nazi-related symbols are banned in European countries (especially Germany) in an effort to curtail neo-Nazism. The term neo-Nazism describes any post-World War II militant, social or political movements seeking to revive the ideology of Nazism in whole or in part. The term neo-Nazism can also refer to the ideology of these movements, which may borrow elements from Nazi doctrine, including ultranationalism, anti-communism, racism, ableism, xenophobia, homophobia,anti-Romanyism, antisemitism, up to initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration ofAdolf Hitler. Neo-Nazism is considered a particular form of far-right politics and right-wing extremism."

text2 = "Coffee contains thousands of chemical compounds, many of which may influence health, said Marilyn Cornelis, an associate professor of preventive medicine at Northwestern University Feinberg School of Medicine. But coffee is also the largest source of caffeine for people in the United States, and that’s where most of the risks associated with coffee consumption come from, she said. Having too much caffeine can cause a racing heart, jitteriness, anxiousness, nausea or trouble sleeping, said Jennifer Temple, a professor of exercise and nutrition sciences at the University at Buffalo. It can also lead to headaches, acid reflux and, at high enough doses, even tremors or vomiting, said Dr. Adrienne Hughes, a medical toxicologist and an assistant professor of emergency medicine at Oregon Health and Science University. But “most people are kind of well tuned with their response to caffeine,” Dr. Cornelis said, and when they begin to experience even mild symptoms of having too much, they cut back. As such, it’s rare to experience dangerous side effects from drinking coffee, Dr. Hughes said. Caffeine overdoses typically result from taking in too much caffeine from concentrated forms, such as powders or supplements, in a short period of time, she said. And in most cases, you would need to consume at least 10,000 milligrams of caffeine — or the equivalent of about 50 to 100 cups of coffee, depending on the strength — for it to be potentially fatal, Dr. Hughes said. Caffeine can cause a short-term increase in your blood pressure and heart rate, particularly if you don’t consume it regularly, she said. But this isn’t usually harmful. Studies show that habitual coffee drinking does not seem to raise blood pressure or the risk of an abnormal heart rhythm in the long run. That said, if you’re prone to abnormal heart rhythms, or if you notice palpitations after having caffeine, you may be more sensitive to its effects and should not consume more than you’re used to, or ingest large doses from concentrated sources, like supplements or energy shots, Dr. Hughes said. And having too much caffeine while pregnant is associated with an increased risk of miscarriage, Dr. van Dam said."
from summa.summarizer import summarize
from summa import keywords

# Define length of the summary as a proportion of the text
print("\n ------------------ Summarize ratio 0.2-----------------")
print(summarize(text2, ratio=0.2))

print("\n ------------------ Summarize words 50 -----------------")
print(summarize(text2, words=50))

print("\nKeywords:\n",keywords.keywords(text2))
# to print the top 3 keywords
print("\nTop 3 Keywords:\n",keywords.keywords(text2,words=3))

